export const response = {
  data: [
    {
      "seller-sku": "028332692762-UPC",
      "fulfillment-channel-sku": "B07W53GGV8",
      asin: "B07W53GGV8",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694216-UPC",
      "fulfillment-channel-sku": "B07W551BN1",
      asin: "B07W551BN1",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694100-UPC",
      "fulfillment-channel-sku": "B07W55BHFV",
      asin: "B07W55BHFV",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692625-UPC",
      "fulfillment-channel-sku": "B07W426G1V",
      asin: "B07W426G1V",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694230",
      "fulfillment-channel-sku": "X0029SRDD9",
      asin: "B07W54S2MR",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692762",
      "fulfillment-channel-sku": "X0029QLPN5",
      asin: "B07W53GGV8",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692571",
      "fulfillment-channel-sku": "X0029QLPMV",
      asin: "B07W5524VB",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692632-UPC",
      "fulfillment-channel-sku": "B07W55HFRF",
      asin: "B07W55HFRF",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332681070",
      "fulfillment-channel-sku": "B084Y7VWMT",
      asin: "B084Y7VWMT",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692588-UPC",
      "fulfillment-channel-sku": "B07W3LKK55",
      asin: "B07W3LKK55",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692687",
      "fulfillment-channel-sku": "X002AX9773",
      asin: "B07W427PNM",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694155",
      "fulfillment-channel-sku": "X0029SRDCF",
      asin: "B07W545X2S",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332681155",
      "fulfillment-channel-sku": "B084YJPG2T",
      asin: "B084YJPG2T",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692731-UPC",
      "fulfillment-channel-sku": "B07W4269F7",
      asin: "B07W4269F7",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692809-UPC",
      "fulfillment-channel-sku": "B07W52Z8J9",
      asin: "B07W52Z8J9",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "18",
    },
    {
      "seller-sku": "028332694230-stickerless",
      "fulfillment-channel-sku": "B07W54S2MR",
      asin: "B07W54S2MR",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692601",
      "fulfillment-channel-sku": "X0029OXBG1",
      asin: "B07VZF8343",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332680936",
      "fulfillment-channel-sku": "X002HIVTOZ",
      asin: "B0838N97DF",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332681001",
      "fulfillment-channel-sku": "X002HIVTP9",
      asin: "B0838N424R",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694162",
      "fulfillment-channel-sku": "X0029SRCPX",
      asin: "B07W52JY5B",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694094",
      "fulfillment-channel-sku": "X0029Q3AAV",
      asin: "B07W1JQMR1",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692557",
      "fulfillment-channel-sku": "X0029OXBGB",
      asin: "B07W53ZL68",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692564",
      "fulfillment-channel-sku": "X0029QLPWV",
      asin: "B07W426ZYN",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694162-UPC",
      "fulfillment-channel-sku": "B07W52JY5B",
      asin: "B07W52JY5B",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692601-UPC",
      "fulfillment-channel-sku": "B07VZF8343",
      asin: "B07VZF8343",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692540",
      "fulfillment-channel-sku": "X0029QLQAH",
      asin: "B07W1JNGM2",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692649",
      "fulfillment-channel-sku": "X0029YDGPR",
      asin: "B07W3LK73G",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692618",
      "fulfillment-channel-sku": "X0029OXBGL",
      asin: "B07W547H9M",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "1",
    },
    {
      "seller-sku": "028332692663-UPC",
      "fulfillment-channel-sku": "B07W52SN3R",
      asin: "B07W52SN3R",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694124-UPC",
      "fulfillment-channel-sku": "B07W55948R",
      asin: "B07W55948R",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692595-UPC",
      "fulfillment-channel-sku": "B07W3LKMCC",
      asin: "B07W3LKMCC",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692571-UPC",
      "fulfillment-channel-sku": "B07W5524VB",
      asin: "B07W5524VB",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692809",
      "fulfillment-channel-sku": "X0029OX67Z",
      asin: "B07W52Z8J9",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692540-UPC",
      "fulfillment-channel-sku": "B07W1JNGM2",
      asin: "B07W1JNGM2",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692618-UPC",
      "fulfillment-channel-sku": "B07W547H9M",
      asin: "B07W547H9M",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692748",
      "fulfillment-channel-sku": "X0029NV1JB",
      asin: "B07W54QPDR",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692793-UPC",
      "fulfillment-channel-sku": "B07W55KC84",
      asin: "B07W55KC84",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692557-UPC",
      "fulfillment-channel-sku": "B07W53ZL68",
      asin: "B07W53ZL68",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692748-UPC",
      "fulfillment-channel-sku": "B07W54QPDR",
      asin: "B07W54QPDR",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694193-UPC",
      "fulfillment-channel-sku": "B07W552R8D",
      asin: "B07W552R8D",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692694",
      "fulfillment-channel-sku": "X002AY9M0J",
      asin: "B07W3LJS36",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694117-UPC",
      "fulfillment-channel-sku": "B07W54QPDP",
      asin: "B07W54QPDP",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694117",
      "fulfillment-channel-sku": "X0029SRF05",
      asin: "B07W54QPDP",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692724-UPC",
      "fulfillment-channel-sku": "B07W3LKHYB",
      asin: "B07W3LKHYB",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692717",
      "fulfillment-channel-sku": "X002AX9863",
      asin: "B07W52HKF9",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692700",
      "fulfillment-channel-sku": "X002AX985T",
      asin: "B07W3LK62M",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692595",
      "fulfillment-channel-sku": "X0029SJWV5",
      asin: "B07W3LKMCC",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694131-UPC",
      "fulfillment-channel-sku": "B07W426Q1G",
      asin: "B07W426Q1G",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694124",
      "fulfillment-channel-sku": "X0029SREZL",
      asin: "B07W55948R",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694070-UPC",
      "fulfillment-channel-sku": "B07W52PSZB",
      asin: "B07W52PSZB",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694087-UPC",
      "fulfillment-channel-sku": "B07W55SVM8",
      asin: "B07W55SVM8",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692670",
      "fulfillment-channel-sku": "X002AX96SD",
      asin: "B07W567H6G",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332681353",
      "fulfillment-channel-sku": "X002HIVSQ9",
      asin: "B0838NNH11",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332681179",
      "fulfillment-channel-sku": "X002HIVSPZ",
      asin: "B0838MQYK4",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694193",
      "fulfillment-channel-sku": "X0029P5P0F",
      asin: "B07W552R8D",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692816",
      "fulfillment-channel-sku": "X0029YE0BV",
      asin: "B07W426B98",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692632",
      "fulfillment-channel-sku": "X0029OX6RZ",
      asin: "B07W55HFRF",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692533-UPC",
      "fulfillment-channel-sku": "B07W426WV1",
      asin: "B07W426WV1",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692823",
      "fulfillment-channel-sku": "X0029YE0BL",
      asin: "B07W4272FK",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332681162",
      "fulfillment-channel-sku": "X002HIVSQJ",
      asin: "B0838NSNQ3",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692533",
      "fulfillment-channel-sku": "X0029RLUEX",
      asin: "B07W426WV1",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692625",
      "fulfillment-channel-sku": "X0029RLUF7",
      asin: "B07W426G1V",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694094-stickerless",
      "fulfillment-channel-sku": "B07W1JQMR1",
      asin: "B07W1JQMR1",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692588",
      "fulfillment-channel-sku": "X0029NV1PF",
      asin: "B07W3LKK55",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694179-UPC",
      "fulfillment-channel-sku": "B07W526PQ6",
      asin: "B07W526PQ6",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694254",
      "fulfillment-channel-sku": "X0029RU5LH",
      asin: "B07W54MC1Z",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694186",
      "fulfillment-channel-sku": "X0029Q3B0P",
      asin: "B07W533RSK",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694087",
      "fulfillment-channel-sku": "X0029P5QDB",
      asin: "B07W55SVM8",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692656-UPC",
      "fulfillment-channel-sku": "B07W425KWR",
      asin: "B07W425KWR",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694070",
      "fulfillment-channel-sku": "X0029P5PS7",
      asin: "B07W52PSZB",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692656",
      "fulfillment-channel-sku": "X0029NUVK1",
      asin: "B07W425KWR",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694179",
      "fulfillment-channel-sku": "X0029P5OYR",
      asin: "B07W526PQ6",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694247-UPC",
      "fulfillment-channel-sku": "B07W1JQ1DV",
      asin: "B07W1JQ1DV",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "1",
    },
    {
      "seller-sku": "028332681186",
      "fulfillment-channel-sku": "X002HIV3GT",
      asin: "B0838NF5F3",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692793",
      "fulfillment-channel-sku": "X0029NUUXT",
      asin: "B07W55KC84",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694223-UPC",
      "fulfillment-channel-sku": "B07W533NL1",
      asin: "B07W533NL1",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694209-UPC",
      "fulfillment-channel-sku": "B07W667D9P",
      asin: "B07W667D9P",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692755",
      "fulfillment-channel-sku": "X0029OXAIP",
      asin: "B07W426KBW",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694148-UPC",
      "fulfillment-channel-sku": "B07W53FRHW",
      asin: "B07W53FRHW",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694216",
      "fulfillment-channel-sku": "X0029P5OZ1",
      asin: "B07W551BN1",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694209",
      "fulfillment-channel-sku": "X0029QUBD5",
      asin: "B07W667D9P",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694186-UPC",
      "fulfillment-channel-sku": "B07W533RSK",
      asin: "B07W533RSK",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694261",
      "fulfillment-channel-sku": "X0029QUBCV",
      asin: "B07VZF9SYC",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692564-UPC",
      "fulfillment-channel-sku": "B07W426ZYN",
      asin: "B07W426ZYN",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692731",
      "fulfillment-channel-sku": "X0029SJZTT",
      asin: "B07W4269F7",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692649-UPC",
      "fulfillment-channel-sku": "B07W3LK73G",
      asin: "B07W3LK73G",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694131",
      "fulfillment-channel-sku": "X0029SRCOJ",
      asin: "B07W426Q1G",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694155-UPC",
      "fulfillment-channel-sku": "B07W545X2S",
      asin: "B07W545X2S",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694223",
      "fulfillment-channel-sku": "X0029P5PTL",
      asin: "B07W533NL1",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692755-UPC",
      "fulfillment-channel-sku": "B07W426KBW",
      asin: "B07W426KBW",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692663",
      "fulfillment-channel-sku": "X0029QLKI5",
      asin: "B07W52SN3R",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692816-UPC",
      "fulfillment-channel-sku": "B07W426B98",
      asin: "B07W426B98",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "26",
    },
    {
      "seller-sku": "028332694148",
      "fulfillment-channel-sku": "X0029P5OZV",
      asin: "B07W53FRHW",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694247",
      "fulfillment-channel-sku": "X0029Q3B0Z",
      asin: "B07W1JQ1DV",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694254-UPC",
      "fulfillment-channel-sku": "B07W54MC1Z",
      asin: "B07W54MC1Z",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692823-UPC",
      "fulfillment-channel-sku": "B07W4272FK",
      asin: "B07W4272FK",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332692724",
      "fulfillment-channel-sku": "X0029SJWVF",
      asin: "B07W3LKHYB",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694100",
      "fulfillment-channel-sku": "X0029P5OZL",
      asin: "B07W55BHFV",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694636-UPC",
      "fulfillment-channel-sku": "B07W425S4M",
      asin: "B07W425S4M",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
    {
      "seller-sku": "028332694421",
      "fulfillment-channel-sku": "X0029RU5MV",
      asin: "B07W52KYF9",
      "condition-type": "NewItem",
      "Warehouse-Condition-code": "SELLABLE",
      "Quantity Available": "0",
    },
  ],
};
