export const response = [
  {
    "item-name":
      'SoHome Summer Holiday Buffalo Checkered Tablecloth, Stylish Festive Tablecloth, Stain Resistant/Machine Washable Polyester, 60"x144" Rectangle Navy/White',
    "item-description":
      "Create the perfect table setting with the Buffalo Check tablecloth by SoHome. The trendy and charming buffalo check pattern makes the perfect backdrop for your dinnerware and will also complement your modern farmhouse d�cor. Made with a cotton-rich, heavyweight fabric that is water repellent, stain resistant and fade resistant. This table cover is perfect for festive brunches, everyday meals, holiday parties and formal dinners. Available in a variety of sizes and colors to best suit your d�cor needs.",
    "listing-id": "1116XLSQAYQ",
    "seller-sku": "028332733120",
    price: "29.99",
    quantity: "",
    "open-date": "2020-11-16 11:44:35 PST",
    "image-url": "",
    "item-is-marketplace": "y",
    "product-id-type": "3",
    "zshop-shipping-fee": "",
    "item-note": "",
    "item-condition": "11",
    "zshop-category1": "",
    "zshop-browse-path": "",
    "zshop-storefront-feature": "",
    asin1: "B08DGY67Z6",
    asin2: "",
    asin3: "",
    "will-ship-internationally": "",
    "expedited-shipping": "",
    "zshop-boldface": "",
    "product-id": "028332733120",
    "bid-for-featured-placement": "",
    "add-delete": "",
    "pending-quantity": "",
    "fulfillment-channel": "AMAZON_NA",
    "Business Price": "",
    "Quantity Price Type": "",
    "Quantity Lower Bound 1": "",
    "Quantity Price 1": "",
    "Quantity Lower Bound 2": "",
    "Quantity Price 2": "",
    "Quantity Lower Bound 3": "",
    "Quantity Price 3": "",
    "Quantity Lower Bound 4": "",
    "Quantity Price 4": "",
    "Quantity Lower Bound 5": "",
    "Quantity Price 5": "",
    "merchant-shipping-group": "Default-Template",
    "Progressive Price Type": "",
    "Progressive Lower Bound 1": "",
    "Progressive Price 1": "",
    "Progressive Lower Bound 2": "",
    "Progressive Price 2": "",
    "Progressive Lower Bound 3": "",
    "Progressive Price 3": "",
  },
  {
    "item-name":
      'SoHome Summer Buffalo Checkered Tablecloth, Festive Holiday Tablecloth, Stain Resistant/Machine Washable Polyester, 60"x144" Rectangle Red/White',
    "item-description":
      "Create the perfect table setting with the Buffalo Check tablecloth by SoHome. The trendy and charming buffalo check pattern makes the perfect backdrop for your dinnerware and will also complement your modern farmhouse d�cor. Made with a cotton-rich, heavyweight fabric that is water repellent, stain resistant and fade resistant. This table cover is perfect for festive brunches, everyday meals, holiday parties and formal dinners. Available in a variety of sizes and colors to best suit your d�cor needs.",
    "listing-id": "1116XMBSZ82",
    "seller-sku": "028332733137",
    price: "29.99",
    quantity: "",
    "open-date": "2020-11-16 11:02:52 PST",
    "image-url": "",
    "item-is-marketplace": "y",
    "product-id-type": "3",
    "zshop-shipping-fee": "",
    "item-note": "",
    "item-condition": "11",
    "zshop-category1": "",
    "zshop-browse-path": "",
    "zshop-storefront-feature": "",
    asin1: "B08DG7Z9BG",
    asin2: "",
    asin3: "",
    "will-ship-internationally": "",
    "expedited-shipping": "",
    "zshop-boldface": "",
    "product-id": "028332733137",
    "bid-for-featured-placement": "",
    "add-delete": "",
    "pending-quantity": "",
    "fulfillment-channel": "AMAZON_NA",
    "Business Price": "",
    "Quantity Price Type": "",
    "Quantity Lower Bound 1": "",
    "Quantity Price 1": "",
    "Quantity Lower Bound 2": "",
    "Quantity Price 2": "",
    "Quantity Lower Bound 3": "",
    "Quantity Price 3": "",
    "Quantity Lower Bound 4": "",
    "Quantity Price 4": "",
    "Quantity Lower Bound 5": "",
    "Quantity Price 5": "",
    "merchant-shipping-group": "Default-Template",
    "Progressive Price Type": "",
    "Progressive Lower Bound 1": "",
    "Progressive Price 1": "",
    "Progressive Lower Bound 2": "",
    "Progressive Price 2": "",
    "Progressive Lower Bound 3": "",
    "Progressive Price 3": "",
  },
  {
    "item-name":
      'SoHome Summer Buffalo Checkered Tablecloth, Holiday Picnic Stain Resistant/Machine Washable Polyester, 70" Round Black/White',
    "item-description":
      "Create the perfect table setting with the Buffalo Check tablecloth by SoHome. The trendy and charming buffalo check pattern makes the perfect backdrop for your dinnerware and will also complement your modern farmhouse d�cor. Made with a cotton-rich, heavyweight fabric that is water repellent, stain resistant and fade resistant. This table cover is perfect for festive brunches, everyday meals, holiday parties and formal dinners. Available in a variety of sizes and colors to best suit your d�cor needs.",
    "listing-id": "1116XME958S",
    "seller-sku": "028332733144",
    price: "19.99",
    quantity: "",
    "open-date": "2020-11-16 10:23:26 PST",
    "image-url": "",
    "item-is-marketplace": "y",
    "product-id-type": "3",
    "zshop-shipping-fee": "",
    "item-note": "",
    "item-condition": "11",
    "zshop-category1": "",
    "zshop-browse-path": "",
    "zshop-storefront-feature": "",
    asin1: "B08DGY5RN5",
    asin2: "",
    asin3: "",
    "will-ship-internationally": "",
    "expedited-shipping": "",
    "zshop-boldface": "",
    "product-id": "028332733144",
    "bid-for-featured-placement": "",
    "add-delete": "",
    "pending-quantity": "",
    "fulfillment-channel": "AMAZON_NA",
    "Business Price": "",
    "Quantity Price Type": "",
    "Quantity Lower Bound 1": "",
    "Quantity Price 1": "",
    "Quantity Lower Bound 2": "",
    "Quantity Price 2": "",
    "Quantity Lower Bound 3": "",
    "Quantity Price 3": "",
    "Quantity Lower Bound 4": "",
    "Quantity Price 4": "",
    "Quantity Lower Bound 5": "",
    "Quantity Price 5": "",
    "merchant-shipping-group": "Default-Template",
    "Progressive Price Type": "",
    "Progressive Lower Bound 1": "",
    "Progressive Price 1": "",
    "Progressive Lower Bound 2": "",
    "Progressive Price 2": "",
    "Progressive Lower Bound 3": "",
    "Progressive Price 3": "",
  },
  {
    "item-name":
      'SoHome Summer Buffalo Checkered Tablecloth, Festive Holiday Tablecloth, Stain Resistant/Machine Washable Polyester, 70" Round Red/Black',
    "item-description":
      "Create the perfect table setting with the Buffalo Check tablecloth by SoHome. The trendy and charming buffalo check pattern makes the perfect backdrop for your dinnerware and will also complement your modern farmhouse d�cor. Made with a cotton-rich, heavyweight fabric that is water repellent, stain resistant and fade resistant. This table cover is perfect for festive brunches, everyday meals, holiday parties and formal dinners. Available in a variety of sizes and colors to best suit your d�cor needs.",
    "listing-id": "1116XLR6SPC",
    "seller-sku": "028332733151",
    price: "19.99",
    quantity: "",
    "open-date": "2020-11-16 10:29:14 PST",
    "image-url": "",
    "item-is-marketplace": "y",
    "product-id-type": "3",
    "zshop-shipping-fee": "",
    "item-note": "",
    "item-condition": "11",
    "zshop-category1": "",
    "zshop-browse-path": "",
    "zshop-storefront-feature": "",
    asin1: "B08DG6VFW9",
    asin2: "",
    asin3: "",
    "will-ship-internationally": "",
    "expedited-shipping": "",
    "zshop-boldface": "",
    "product-id": "028332733151",
    "bid-for-featured-placement": "",
    "add-delete": "",
    "pending-quantity": "",
    "fulfillment-channel": "AMAZON_NA",
    "Business Price": "",
    "Quantity Price Type": "",
    "Quantity Lower Bound 1": "",
    "Quantity Price 1": "",
    "Quantity Lower Bound 2": "",
    "Quantity Price 2": "",
    "Quantity Lower Bound 3": "",
    "Quantity Price 3": "",
    "Quantity Lower Bound 4": "",
    "Quantity Price 4": "",
    "Quantity Lower Bound 5": "",
    "Quantity Price 5": "",
    "merchant-shipping-group": "Default-Template",
    "Progressive Price Type": "",
    "Progressive Lower Bound 1": "",
    "Progressive Price 1": "",
    "Progressive Lower Bound 2": "",
    "Progressive Price 2": "",
    "Progressive Lower Bound 3": "",
    "Progressive Price 3": "",
  },
];
